common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change_password', views.change_password, name='change_password'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from salary import views
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('salary/', include('salary.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    ]

salary/urls.py
from django.urls import path
from . import views

app_name = 'salary'

urlpatterns = [
    path('', views.index, name='index'),
    path('excelGood/', views.excelIndex, name='excel'),
    path('salary/', views.salary, name='salary'),

]

salary/models.py
from django.db import models

# Create your models here.
class Salary(models.Model):
    models.IntegerField(blank=True, null=True)
    models.FloatField(blank=True, null=True)
    # 월급계산서 이름
    salary_name = models.TextField(default='', blank=True, null=False)
    # 사번
    employee_number = models.TextField(default='', blank=True, null=False)
    # 사원명
    name = models.CharField(blank=True, null=True, max_length=4)
    # 사원코드
    employee_code = models.TextField(default='', blank=True, null=False)
    # 지금액계
    total_payment = models.TextField(default='', blank=True, null=False)
    # 공제액계
    total_deduction = models.TextField(default='', blank=True, null=False)
    # 차인지급액
    actual_payment = models.TextField(default='', blank=True, null=False)
    # 입사일 호봉 직급 부서
    entered_date = models.TextField(default='', blank=True, null=False)
    salary_step = models.TextField(default='', blank=True, null=False)
    rank = models.TextField(default='', blank=True, null=False)
    department = models.TextField(default='', blank=True, null=False)

    # 기본급 , 명절 지원금 , 성과급
    normal = models.TextField(default='', blank=True, null=False)
    holiday_subsidy = models.TextField(default='', blank=True, null=False)
    incentive = models.TextField(default='', blank=True, null=False)

    # 기타급여정산분  #자녀학자금지원
    other_salary_settlement = models.TextField(default='', blank=True, null=False)
    school_expenses = models.TextField(default='', blank=True, null=False)

    # 면허수당 #시간외수당 #당직수당 #연차수당
    license_allowance = models.TextField(default='', blank=True, null=False)
    overtime_allowance = models.TextField(default='', blank=True, null=False)
    duty_allowance = models.TextField(default='', blank=True, null=False)
    annual_allowance = models.TextField(default='', blank=True, null=False)

    # 장기근속/포상금, 기타수당 , 기타1(지급) 산전휴가/육아휴직 , 식대
    long_term_reward = models.TextField(default='', blank=True, null=False)
    other_allowance = models.TextField(default='', blank=True, null=False)
    other_salary_payments = models.TextField(default='', blank=True, null=False)
    maternity_leave = models.TextField(default='', blank=True, null=False)
    meals = models.TextField(default='', blank=True, null=False)

    # 여기부터 공제
    # 국민연금 , 건강보험, 고용보험 , 장기요양보험료
    national_pension = models.TextField(default='', blank=True, null=False)
    health_insurance_premium = models.TextField(default='', blank=True, null=False)
    employment_insurance = models.TextField(default='', blank=True, null=False)
    long_term_care_premium = models.TextField(default='', blank=True, null=False)

    # 소득세, 지방소득세, 연말정산소득세, 연말정산지방소득세, 연말정산농특세
    income_tax = models.TextField(default='', blank=True, null=False)
    local_income_tax = models.TextField(default='', blank=True, null=False)
    Year_end_settlement_income_tax = models.TextField(default='', blank=True, null=False)
    local_income_tax_for_year_end_settlement = models.TextField(default='', blank=True, null=False)
    year_and_settlement_agricultural_special_tax = models.TextField(default='', blank=True, null=False)

    # 사우회비, 주택자금상환 , 기타1, 기타2, 건강보험료정산, 장기요양보험정산
    membership_fee = models.TextField(default='', blank=True, null=False)
    repayment_of_hosing_funds = models.TextField(default='', blank=True, null=False)
    other_one = models.TextField(default='', blank=True, null=False)
    other_two = models.TextField(default='', blank=True, null=False)
    health_insurance_premium_settlement = models.TextField(default='', blank=True, null=False)
    long_term_care_premium_settlement = models.TextField(default='', blank=True, null=False)

    def __str__(self):
        return self.name


class Go(models.Model):
    employee_number = models.TextField()
    name = models.CharField(max_length=4)
    Code = models.TextField()
    total_payment = models.TextField(blank=True, null=True)
    total_deduction = models.TextField(blank=True, null=True)
    actual_payment = models.TextField(blank=True, null=True)
    last_payment = models.TextField(blank=True, null=True)
    other_salary = models.TextField(blank=True, null=True)
    meals = models.TextField(blank=True, null=True)
    maternity_leave = models.TextField(blank=True, null=True)
    Incentive = models.TextField(blank=True, null=True)
    payroll = models.TextField(blank=True, null=True)
    school_expenses = models.TextField(blank=True, null=True)
    license_allowance = models.TextField(blank=True, null=True)
    overtime_allowance = models.TextField(blank=True, null=True)
    duty_allowance = models.TextField(blank=True, null=True)
    annual_allowance = models.TextField(blank=True, null=True)
    other_allowance = models.TextField(blank=True, null=True)
    long_term_reward = models.TextField(blank=True, null=True)
    RSP = models.TextField(blank=True, null=True)
    allowance = models.TextField(blank=True, null=True)
    resident_tax = models.TextField(blank=True, null=True)
    tax_meter = models.TextField(blank=True, null=True)
    health_insurance_premium = models.TextField(blank=True, null=True)
    employment_insurance_premium = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

salary/views.py
from django.shortcuts import render
from .models import Salary
from openpyxl import load_workbook

# Create your views here.
from django.http import HttpResponse


def index(request):
    return render(request, 'common/login.html')

def salary(request):
    """
    pybo 답변등록
    """
    if request.user.get_username()=="admin":
        return render(request, 'salary/excel.html')

    memo_name = request.user.get_username()

    # salary = get_object_or_404( Salary, username=Salary.name)\
    try:
        salary = Salary.objects.get(employee_number=memo_name)
    except:
        return render(request, 'salary/error.html')
    # salary = Salary.objects_or_404(name=memo_name)
    # for key in list(salary.objects()):
    #     if key.value ==None: key.value =''
    # for k,v in salary.items():
    #     if v is None: salary[k]=''
    context = {'salary': salary, 'name': memo_name}
    return render(request, 'salary/salary.html', context)


def excelIndex(request):
    if "GET" == request.method:
        """
               pybo 목록 출력
               """
        return render(request, 'salary/excel.html')


    else:
        excel_file = request.FILES["excel_file"]

        # data_only=Ture로 해줘야 수식이 아닌 값으로 받아온다.
        load_wb = load_workbook(excel_file, data_only=True)

        # 시트 이름으로 불러오기
        load_ws = load_wb['급여보고']
        dict = {}
        dict['salary_name'] = load_ws['H1'].value.split('급')[0].strip()

        # 셀 주소로 값 출력
        # print(load_ws['A1'].value)

        Salary.objects.all().delete()
        rows = load_ws.rows
        for idx,r in enumerate(rows) :
            if idx<3:
                continue
            if r[2].value == None: break
            dict['employee_number'] = r[1].value
            dict['name'] = r[5].value.split()[0]
            dict['employee_code'] = r[6].value
            if r[8].value :dict['total_payment'] = f'{r[8].value:,}'
            if r[9].value :dict['total_deduction'] =f'{r[9].value:,}'
            if r[10].value:dict['actual_payment'] = f'{r[10].value:,}'
            if r[11].value:dict['normal'] = f'{r[11].value:,}'
            if r[34].value:dict['other_one'] = f'{r[34].value:,}' #not change
            if r[13].value:dict['meals'] =f'{r[13].value:,}'
            if r[21].value :dict['maternity_leave'] = f'{r[21].value:,}'
            # if r[23].value :dict['incentive'] = f'{r[23].value:,}' 성과급 없음
            if r[16].value :dict['license_allowance'] = f'{r[16].value:,}'
            if r[17].value :dict['overtime_allowance'] = f'{r[17].value:,}'
            if r[18].value :dict['duty_allowance'] = f'{r[18].value:,}'
            if r[19].value :dict['annual_allowance'] = f'{r[19].value:,}'
            if r[20].value :dict['other_allowance'] = f'{r[20].value:,}'
            if r[22].value :dict['long_term_reward'] = f'{r[22].value:,}'
            if r[15].value :dict['school_expenses'] = f'{r[15].value:,}'
            if r[25].value :dict['income_tax'] = f'{r[25].value:,}'
            if r[32].value :dict['national_pension'] = f'{r[32].value:,}'
            if r[31].value :dict['employment_insurance'] = f'{r[31].value:,}'
            if r[30].value :dict['health_insurance_premium'] = f'{r[30].value:,}'
            if r[26].value :dict['local_income_tax'] = f'{r[26].value:,}'
            # if r[34].value :dict['long_term_care_premium'] = f'{r[34].value:,}' 장기요양보험료
            if r[33].value :dict['membership_fee'] = f'{r[33].value:,}'
            # if r[29].value :dict['repayment_of_hosing_funds'] = f'{r[29].value:,}'
            if r[27].value: dict['Year_end_settlement_income_tax'] = f'{r[27].value:,}'
            if r[28].value: dict['local_income_tax_for_year_end_settlement'] = f'{r[28].value:,}'
            if r[20].value: dict['other_allowance'] = f'{r[20].value:,}'
            # if r[35].value :dict['health_insurance_premium_settlement'] = f'{r[35].value:,}'
            # if r[36].value :dict['long_term_care_premium_settlement'] = f'{r[36].value:,}'
            # dict['department'] = r[40].value 부서
            # dict['entered_date'] = r[47].value 입사일 안됨
            dict['rank'] = r[7].value
            Salary(**dict).save()

        return render(request, 'salary/excel.html', {})

templates/salary/error.html
{% extends 'base.html' %}

{% block content %}
  <h3>
      잘못된 사원번호로 회원가입 했습니다.
      로그아웃하시고 회원가입을 다시 해주세요.
  </h3>
{% endblock %}

templates/salary/excel.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'exc.css' %}">
    <title>급여명세서!</title>
</head>
<body style="margin:0;">
{% include "navbar.html" %}

<form class="filebox" action="{% url "salary:excel" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
    <div class="instruction"> <h1><strong>Excel 급여보고 파일 업로드 메뉴얼</strong></h1> 엑셀 파일 선택 ->업로드 <br> * 엑셀 파일 sheet 이름을 급여보고 할 것 </div>
           <div> <input class="upload-name" value="파일선택" disabled="disabled">

            <label for="ex_filename">파일선택</label>
            <input type="file"
                   id="ex_filename" class="upload-hidden"
                   title="Upload excel file"
                   name="excel_file"
                   required="required">


            <label for="ex_submit" class="submit">업로드</label>
            <input type="submit"
                   id="ex_submit" class="upload-hidden"
                   value="Upload">
               </div>
        </form>

<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'excel.js' %}"></script>
</body>
</html>

templates/salary/salary.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'salary.css' %}">
    <title>급여명세서!</title>
</head>
<body style="margin:0;">
{% include "navbar.html" %}
<div class="board" >
<div style="text-align: center; margin-bottom: 30px"><h1>{{ salary.salary_name }}분 급상여명세서 </h1></div>
    <div class="info" ><div>사원코드: {{ salary.employee_code }}</div><div>사원명: {{ salary.name }}</div><div>입사일: {{ salary.entered_date }}</div></div>
    <div class="info"><div>부서: {{ salary.department }}</div><div>직급: {{ salary.rank }}</div><div>호봉: {{ salary.salary_step }}</div></div>

    <table  >

  <thead>
    <tr style="font-size: 20px">
      <th class="sol" scope="col">지급내역</th>
      <th class="coll" scope="col">지급액</th>
      <th class="sol" scope="col">공제내역</th>
      <th class="col" scope="col">공제액</th>
    </tr>
  </thead>
  <tbody >
    <tr>
      <td >기본급</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.normal }}</td>
      <td>국민연금</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.national_pension }}</td>

    </tr>
    <tr>
      <td>명절지원금</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.holiday_subsidy}}</td>
      <td>건강보험</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.health_insurance_premium}}</td>
    </tr>

  <tr>
      <td>성과급</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.incentive}}</td>
      <td>고용보험</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.employment_insurance }}</td>
    </tr>
    <tr>
      <td>기타급여정산분</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.other_salary_settlement }}</td>
      <td>장기요양보험료</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.long_term_care_premium }}</td>
    </tr>

   <tr>
      <td>자녀학자금지원</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.school_expenses }}</td>
      <td>소득세</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.income_tax }}</td>
    </tr>

   <tr>
       <td>면허수당</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.license_allowance }}</td>
      <td>지방소득세
      </td>
      <td style="text-align: right; padding-right: 5px">{{ salary.local_income_tax }}</td>
    </tr>

   <tr>
      <td>시간외수당</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.overtime_allowance }}</td>
      <td>연말정산소득세</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.Year_end_settlement_income_tax}}</td>
    </tr>
   <tr>
      <td>당직수당</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.duty_allowance }}</td>
      <td>연말정산지방소득세</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.local_income_tax_for_year_end_settlement }}</td>
    </tr>

    <tr>
      <td>연차수당</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.annual_allowance }}</td>
      <td>연말정산농특세</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.year_and_settlement_agricultural_special_tax}}</td>
    </tr>
    <tr>
      <td>장기근속/포상금</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.long_term_reward }}</td>
      <td>사우회비</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.membership_fee }}</td>
    </tr>
    <tr>
      <td>기타수당</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.other_allowance }}</td>
      <td>주택자금상환</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.repayment_of_hosing_funds }}</td>
    </tr>
    <tr>
      <td>기타 1</td>
      <td style="text-align: right; padding-right: 10px"></td>
      <td>기타 1</td>
      <td style="text-align: right; padding-right: 5px"></td>
    </tr>
    <tr>
      <td>산전휴가/육아휴직</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.maternity_leave }}</td>
      <td>기타 2</td>
      <td style="text-align: right; padding-right: 5px"></td>
    </tr>
    <tr>
      <td>식대</td>
      <td style="text-align: right; padding-right: 10px">{{ salary.meals }}</td>
      <td>건강보험료정산</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.health_insurance_premium_settlement }}</td>
    </tr>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>장기요양보험정산</td>
      <td style="text-align: right; padding-right: 5px">{{ salary.long_term_care_premium_settlement }}</td>
    </tr>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>

  <tr style="font-size: 20px">
      <td></td>
      <td></td>
      <th>공제액계</th>
      <td style="text-align: right; padding-right: 5px">{{ salary.total_deduction }}</td>
    </tr>

  <tr style="font-size: 20px">
      <th>지급액계</th>
      <td style="text-align: right; padding-right: 10px">{{ salary.total_payment }}</td>
      <th>차인지급액</th>
      <td style="text-align: right; padding-right: 5px">{{ salary.actual_payment}}</td>
    </tr>
  <tr style="border: none">
      <td>※  귀하의 노고에 감사드립니다</td>
      <td></td>
      <th></th>
      <td style="text-align: right">(주)바커케미칼코리아
</td>
    </tr>
  </tbody>
    </table>
</div>
<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>