common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change_password', views.change_password, name='change_password'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from salary import views
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('salary/', include('salary.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    ]

salary/urls.py
from django.urls import path
from . import views

app_name = 'salary'

urlpatterns = [
    path('', views.index, name='index'),
    path('excelGood/', views.excelIndex, name='excel'),
    path('salary/', views.salary, name='salary'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>바커 급여명세서</title>
</head>
<body style="margin:0;">
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    {% if user.is_authenticated %}

        <a class="navbar-brand" href="{% url 'salary:salary' %}">바커 급여명세서</a>
    {% else %}
        <a class="navbar-brand" href="{% url 'salary:index' %}">바커 급여명세서</a>
    {% endif %}
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-1 " id="navbarNav">
        <ul class="navbar-nav " >
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link text-right" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    <a class="nav-link text-right" href="{% url 'common:change_password' %}">(비밀번호 변경)</a>

                {% else %}
                     <a class="nav-link" href="{% url 'password_reset' %}">비밀번호 찾기</a>
                {% endif %}
                <label style="margin-bottom: 0px ;
            position: absolute; right: 20px; top: 9px;
    display: inline-block; padding: .5em .75em; color: #fff; font-size: inherit;
    line-height: normal; vertical-align: middle; background-color: #1e88e5; cursor: pointer;
    border: 1px solid #ebebeb; border-bottom-color: #e2e2e2; border-radius: .25em; }" for="ex_print">프린트</label>
                <input id="ex_print"  style=" position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip:rect(0,0,0,0); border: 0; " type="button" value="인쇄하기" id="print" onclick="window.print()"/>
            </li>
        </ul>
    </div>
</nav>